# -*- coding: utf-8 -*-
"""Mod 3 HW2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cx2uMuJRmDsNevNnSTGff2T72Vyy1JkK

# Homework 02:  Linear Regression in Theory and Practice

### Due: May 24th @ 11:59PM

In this homework, you’ll work with a simple synthetic regression dataset generated using scikit-learn’s `make_regression` function. Synthetic data is a valuable tool for testing modeling workflows, gaining hands-on experience with regression models, and understanding how factors like noise and training set size impact model performance—particularly when measured by the metrics introduced in Week 1. Because we control how the dataset is generated, we can directly assess how well our model recovers the underlying patterns. You’ll also practice splitting data into training and test sets to evaluate how well your model generalizes to unseen data.

Some questions will require you to consult the scikit-learn documentation. These functions are widely used in machine learning, and becoming comfortable with reading documentation and examples is an essential part of developing fluency with the tools.

As in the first assignment, some tasks are not graded, but that doesn’t mean they are optional. Skipping these steps will weaken your understanding and reduce the long-term value of your effort. Treat every part of the homework seriously—you’ll thank yourself later when you take on real-world projects and more advanced modules.

All homeworks are worth 55 points. There are 18 problems, each worth 3 points, and you get 1 point for free (if you complete the assignment!).
"""

# Useful imports and utilities

import numpy as np
import pandas as pd
import time
import matplotlib.pyplot as plt
import os
import kagglehub
import seaborn as sns

from sklearn.linear_model import LinearRegression
from sklearn.datasets import fetch_california_housing,make_regression
from sklearn.metrics import mean_squared_error, mean_absolute_error, root_mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from tqdm import tqdm

# globals

random_state = 42

# my additions
from scipy.stats import linregress

"""## Problem One: Generate and Visualize a Simple Univariate Regression Dataset

In this problem, you’ll explore scikit-learn’s `make_regression` function, which generates synthetic datasets for testing regression models. You can control key parameters like the number of samples and the noise level (standard deviation of the errors), though some settings—such as the feature value ranges or the true coefficients—are randomly generated or limited in configurability (e.g., you can set the bias, but not the coefficients directly).

Despite these quirks, `make_regression` is widely used for prototyping and examining model behavior under controlled conditions.

Before you begin, take a moment to read the [scikit-learn documentation for `make_regression`](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.make_regression.html) to understand its parameters and capabilities.

### Generate a Univariate Dataset

Use `make_regression` to generate a simple univariate regression dataset with the following parameters:

* `n_samples=20`
* `n_features=1` (implied for univariate)
* `noise=20` (this sets the standard deviation of the errors)
* `bias=0.5` (this sets the y-intercept)
* `random_state=42` (for reproducibility)
* `coef=True` (this returns the underlying model’s coefficients)

Note that when `coef=True`, the function returns a tuple with three values: `X`, `y`, and the  coefficients (in this case, just the slope). Refer to the [documentation](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.make_regression.html) to understand the return format.
"""

# Your code here (you may add additional cells if you wish)
n_samples = 20
bias = 0.5
noise = 20

X, y, coef = make_regression(
    n_samples = n_samples,
    n_features = 1,
    noise = noise,
    bias = bias,
    coef = True,
    random_state = 42
)

"""### Part A

**TODO:** Set `a1a` to the range of `X`, i.e., a tuple `(lb,ub)` (or array) where `lb` is the smallest value in `X` and `ub` is the largest.  
"""

# Your answer here, NOT in the next cell (you may add additional cells if you wish)

a1a = (X.min(), X.max())          # Replace 0,0 with an expression returning the range

# Graded Answer
# DO NOT change this cell in any way

print(f'a1a = {a1a}')

"""### Part B

**TODO:** Set `a1b` to the slope of the underlying model.

Hint: `make_regression` will return the coefficients as an array with one fewer dimensions than `X`; in this case, it is a 0-dimension array whose shape is `()`.  Weird, I know, but this is unusual.  You can pretend it is just a float.
"""

# Your answer here, NOT in the next cell (you may add additional cells if you wish)

a1b = coef       # Replace 0 with an expression returning the slope

# Graded Answer
# DO NOT change this cell in any way

print(f'a1b = {a1b:.4f}')           # Will print to 4 decimal places

"""### Visualizing the Data (Nothing for you to do but think about it!)

The following will create a plot of the dataset, with the regression line (given by the bias and the slope).

**Note:** You will need to complete the previous cell for this to be correct!

"""

# Plot the data points and the regression line

if a1b != 0:        # If you answered the previous questions!

    bias = 0.5

    plt.figure(figsize=(8, 6))
    plt.scatter(X, y, color='blue',label="Data points",marker='.')
    plt.plot(a1a,[bias+a1b*a1a[0],bias+a1b*a1a[1]], color="grey", alpha=0.3,label="Underlying Model",linestyle='--')
    plt.xlabel("X")
    plt.ylabel("y")
    plt.title("Univariate Regression Dataset")
    plt.legend()
    plt.grid(True)
    plt.show()

"""## Problem Two: Run Linear Regression on the Data Set and Evaluate the Results

Now we will use `sklearn`'s `LinearRegression` model to create a model from the dataset. Of course, the **underlying model** has already been
created, but your linear regression won't know that, and it has to determine the best model given the data samples it has.

### Part A: Create and Evaluate a Linear Model

**TODO:**

- Create a linear regression model called simply `model` and train it on `X,y`.
- Set `a2a` to the bias/y-intercept of the model.            

"""

# Your answer here, NOT in the next cell (you may add additional cells if you wish)

model = LinearRegression()
model_fit = model.fit(X,y)

a2a = model.intercept_   # Replace 0 with an expression returning the bias

# Graded Answer
# DO NOT change this cell in any way

print(f'a2a = {a2a:.4f}')           # Will print to 4 decimal places

"""### Part B

**TODO:**

- Set `a2b` to the slope of the model.
- Hint: The coefficients are returned as a 1-dimensional array (unlike `make_regression`!), so you'll need to turn a 1-element array into a scalar.

"""

# Your answer here, NOT in the next cell (you may add additional cells if you wish)

a2b = model.coef_[0]   # Replace 0 with an expression returning the slope

# Graded Answer
# DO NOT change this cell in any way

print(f'a2b = {a2b:.4f}')           # Will print to 4 decimal places

"""### Part C

**TODO:**

- Set `a2c` to the **training MSE** of the model on the dataset.
- Hint: generate an array `y_pred` by using the model to predict the targets from the original `X`, then calculate the mean squared error using the appropriate `sklearn` function.  (Now might be a good time to look at that first code cell to see what I imported for you.)

"""

# Your answer here, NOT in the next cell

model_predict = model.predict(X)

a2c = mean_squared_error(y, model_predict)   # Replace 0 with an expression returning the training mse

# Graded Answer
# DO NOT change this cell in any way

print(f'a2c = {a2c:.4f}')           # Will print to 4 decimal places

"""### Part D

**TODO:** Set `a2d` to the training root mean square error (RMSE).

**Note:** You *can* just take the square root of the MSE, but it is generally better to use library functions than your own calculations (did you look at the first cell imports?).  

"""

# Your answer here, NOT in the next cell (you may add additional cells if you wish)

a2d = root_mean_squared_error(y, model_predict)         # Replace 0 with an expression returning the training rmse

# Graded Answer
# DO NOT change this cell in any way

print(f'a2d = {a2d:.4f}')           # Will print to 4 decimal places

"""### Part E

**TODO:** Set `a2e` to the training mean absolute error (MAE).

"""

# Your answer here, NOT in the next cell (you may add additional cells if you wish)

a2e = mean_absolute_error(y, model_predict)               # Replace 0 with an expression returning the training mae

# Graded Answer
# DO NOT change this cell in any way

print(f'a2e = {a2e:.4f}')           # Will print to 4 decimal places

"""### Part F

**TODO:** Set `a2f` to the coefficient of determination ($R^2$) of the model on the training data (read the docs!).

**Note:** Although it is tempting to use a more "readable" notation such as `45.23%`, it is better to stick to straight-forward
floating-point numbers for percentages, e.g., `0.4523` (and NOT `45.23`), and so we have followed this convention here.  

"""

# Your answer here, NOT in the next cell (you may add additional cells if you wish)

a2f = r2_score(y, model_predict)            # Replace 0 with an expression returning the training r2

# Graded Answer
# DO NOT change this cell in any way

print(f'a2f = {a2f:.4f}')           # Will print to 4 decimal places

"""### Visualizing The Model (Nothing for you to do but think about it!)

We now provide a visualization of the regression line by  adding a plot of the model's regression line in red.

"""

# Plot the data points and the regression line

if a2d != 0:     # If you answered the previous questions!

    plt.figure(figsize=(8, 6))
    plt.scatter(X, y, color='blue',label="Data points",marker='.')
    plt.plot(a1a,[bias+a1b*a1a[0],bias+a1b*a1a[1]], color="grey", alpha=0.3,label="Underlying Model",linestyle='--')
    plt.plot(a1a,[model.intercept_+model.coef_[0]*a1a[0],model.intercept_+model.coef_[0]*a1a[1]], color="red", label="Regression Model")

    plt.xlabel("X")
    plt.ylabel("y")
    plt.title("Univariate Regression Dataset")
    plt.legend()
    plt.grid(True)
    plt.show()

    # Just some stats
    print(f'Underlying model = {np.around(bias,4)} + {np.around(a1b,4)} * x')
    print(f'Linear model     = {np.around(model.intercept_,4)} + {np.around(model.coef_[0],4)} * x')
    # print(f'MSE              = {mean_squared_error(y,y_pred):.4f}')
    print(f'R^2              = {np.around(model.score(X, y),4):.4f}')

"""![Screenshot 2025-05-19 at 5.41.25 PM.png](attachment:d9e9ab3d-eb15-4d98-a29f-a3e9d3b20227.png)

### Pause and Ponder (no need to write answers, just think about these):  
- Why does the linear regression line not match the underlying model?
- Which parameters (`bias`, `n_samples`,`noise`) do you think affect how well the regression model matches the actual model?
- What changes to these parameters would result in a more accurate match between underlying and regression models?

## Problem Three:  How well does it generalize?

The **most important issue** in making useful models is to ensure that they are able to **generalize to new data from the same domain.**  For example, if you create a model from a housing price dataset,
you want it to be able to predict what price could be obtained if you build new houses with particular features. You will learn techniques for judging how well models generalize in
the next few lessons, and it will continue to be a crucial issue going forward.

For now, since we have the underlying model (which never happens IRL!) we can easily create new data samples with the same characteristics as the set we used for training.

### Part A

**TODO:**

- Complete the following stub to create a function to create new points to add the data set, with all the same parameters as the underlying model, following these steps:
    1. Create a random number within the existing range of`X`, using `np.random.uniform`
    2. Use the bias and slope of the underlying model to find the point (x,y) on the regression line (which is the prediction for y given x)
    3. Add an error distributed normally with mean 0 and std `noise` to y
    4. Return (x,y)

- Test it by running the cell repeatedly to see the results (we are not setting a random seed, so it will generate random answers)

- Generate 5 new data points (we'll use these below as a **test set**) and assign them to ndarrays `X_new` and `y_new`
- Hint: create a list of pairs and split using `zip(* ...)`

- Set `a3a` to the first 2 values in `X_new`.
"""

# Your code here (add additional cells if you wish)
# define the function
def make_new_points():
  # choose new x's at random
  X_points = np.random.uniform(X.min(), X.max())
  # find the point on the regression line
  y_points = bias + coef * X_points
  # adds random erors
  y_points = y_points + np.random.normal(0, noise)
  # return the new points
  return (X_points, y_points)

# generate new data points
new_points = [make_new_points() for i in range(5)]
print(new_points)

# testing without random_states
# first: [(-0.8937654887965458, np.float64(-18.679102841201694)), (1.3057647432379311, np.float64(77.56445964854964)), (1.0919074139972906, np.float64(20.96038774272593)), (-1.2789455435920174, np.float64(-69.44103623016876)), (-0.2037893457497495, np.float64(-26.852936801096448))]
# second: [(-1.683817889559884, np.float64(-53.31265180070453)), (-1.2249904576628707, np.float64(-62.72732890693371)), (0.2368795991622905, np.float64(-14.629801605558399)), (-1.0657141401725068, np.float64(-51.81125094244673)), (0.7566015898440286, np.float64(64.20089748597778))]
# third: [(-0.3610904554646064, np.float64(-29.23455986414666)), (-1.082004118423999, np.float64(-64.7021121749776)), (-0.3643936640880714, np.float64(15.822261923154045)), (-1.4037141412573484, np.float64(-38.17975024474)), (-0.9232777936995485, np.float64(-14.496164487753017))]

# assign to new values X_new, y_new
X_new, y_new = zip(*new_points)

# make them arrays
X_new = np.array(X_new).reshape(-1,1)
y_new = np.array(y_new)

# Your answer here, NOT in the next cell (you may add additional cells if you wish)

a3a = X_new[:2]   # Replace [] with an expression returning the first two values in X_new

# Graded Answer
# DO NOT change this cell in any way

print(f'a3a = {a3a}')

"""### Visualize the Data (Nothing for you to do but think about it!)

We now add our new data points in green, in addition to what we displayed in Problem Two.

"""

# Plot the data points and the regression line

if len(a3a) > 0:        # If you answered the previous questions!

    plt.figure(figsize=(8, 6))
    plt.scatter(X, y, color='blue',label="Data points",marker='.')
    plt.scatter(X_new, y_new, color='green',label="New Data",marker='x')
    plt.plot(a1a,[bias+a1b*a1a[0],bias+a1b*a1a[1]], color="grey", alpha=0.3,label="Underlying Model",linestyle='--')
    plt.plot(a1a,[model.intercept_+model.coef_[0]*a1a[0],model.intercept_+model.coef_[0]*a1a[1]], color="red", label="Regression Model")

    plt.xlabel("X")
    plt.ylabel("y")
    plt.title("Univariate Regression Dataset")
    plt.legend()
    plt.grid(True)
    plt.show()

"""![Screenshot 2025-05-19 at 5.41.41 PM.png](attachment:618732e1-1d73-48b5-8a66-7f9fc2cdd14e.png)

### Part B

**TODO:**

- Assign the MSE on the new data to `a3b` (we'll later call this the "test MSE").
- Hint: When you "roll your own" datasets using ndarrays, you will generally have to reshape them using `.reshape(-1,1)` because `sklearn` models expect a column array, not a "normal" array.
"""

# Your answer here, NOT in the next cell (you may add additional cells if you wish)
# need to make predictions on the new data
model_predict_new = model.predict(X_new)

a3b = mean_squared_error(y_new, model_predict_new)   # Replace 0 with an expression returning the mse

# Graded Answer
# DO NOT change this cell in any way

print(f'a3b = {a3b:.4f}')           # Will print to 4 decimal places

"""### Part C:  Let's Compare Metrics

We now have three related values:
- Noise = standard deviation of "errors" between the data and the underlying model
- Training MSE of the linear model on the dataset
- Testing MSE of the linear model on new data generated with the same parameters as the original dataset

**TODO:**  Answer the following multiple-choice problems by assigning the variable to the  **most accurate** statement.

#### C1) Comparing the Two MSEs

Why might the training MSE be *larger* than the testing MSE in this scenario?

1. These should be exactly the same, so there must have been an error somewhere.  
2.  With only 20 training points, a few unusual data points (outliers) can increase the average training error; meanwhile, the small test set of 5 points could *by chance* lead to smaller errors overall.  
3. There is always a positive bias in the regression line, so it will always be larger.
4.  There is very little relationship between these two numbers, so the fact that they are close to each other must be an accident.  
"""

# Your answer here, NOT in the next cell (you may add additional cells if you wish)

a3c1 = 2              # Replace the 0 with one of 1, 2, 3, 4

# Graded Answer
# DO NOT change this cell in any way

print(f'a3c1 = {a3c1}')

"""#### C2) Understanding the Noise Parameter

Suppose a dataset has been generated using `make_regression` with `noise = 20`.  

Which statement best explains the significance of the noise parameter when interpreting the MSE of models trained on this dataset?  

1. The square of the noise parameter, $20^2 = 400$, represents the irreducible noise in the data; no model can achieve an MSE lower than this on average.  
2. A noise standard deviation of 20 means the MSE can eventually be reduced to 0 with enough data.  
3. MSE measures the *average* absolute errors, so having $\sigma = 20$ implies the MSE will always equal 20.  
4. If the noise is 20, then it’s possible to create a model with training and testing MSEs that are *exactly* 400 with sufficient effort.  

"""

# Your answer here, NOT in the next cell (you may add additional cells if you wish)

# 1. was going to go with this until the "no model can achieve" because I think it is possible to be smaller than 400 because of the randomness - seems too absolute, but maybe because of the "on average" statement it's True
# 2. since the model has noise built into it, more data won't change this
# 3. mean squared error isn't an average - it's the square of the sum of all errors, this sounds more like mean absolute error
# 4. also doesn't seem right because of the randomness of the data

a3c2 =  1              # Replace the 0 with one of 1, 2, 3, 4

# Graded Answer
# DO NOT change this cell in any way

print(f'a3c2 = {a3c2}')

"""#### C3) The Role of Dataset Size

You fitted a linear model on **20** training points and tested it on **5** new points, both drawn from a process with noise standard deviation 20 (variance 400).  

What would happen if we repeated the same experiment with more training/testing points or with even fewer points?  
In other words, **how does dataset size affect the measured MSE values?**

1.  If the training set is small, the MSE will always be *exactly* 400 for both training and test sets, since there’s too little data to deviate from the noise variance.  

2.  Collecting more data actively *lowers* the true noise standard deviation from 20 to something smaller, guaranteeing an MSE below 400.  
3. If you have fewer than 30 data points, the training MSE must always exceed 400 and the test MSE must always be *less* than 400.  
4. Small sample sizes can cause large swings in MSE, sometimes pushing the training MSE above 400 while letting a tiny test set fall below 400 by chance. With larger datasets, the MSE typically stabilizes closer to 400.  
"""

# Your answer here, NOT in the next cell (you may add additional cells if you wish)

# 1. MSE is sensitive to noise, so small datasets would likely make the MSE smaller (since there's less possible error to calculate)
# 2. more data doesn't change the inherent noise added into the data at generation
# 3. I don't remember learning any rules regarding n thresholds so I don't think this is right
# 4. in the live session we talked about how MSE is very sensitive to outliers, I think this is the correct answer

a3c3 = 4              # Replace the 0 with one of 1, 2, 3, 4

# Graded Answer
# DO NOT change this cell in any way

print(f'a3c3 = {a3c3}')

"""## Problem Four: Linear Regression on an Actual Dataset (finally!)

Let's consider applying what we have learned to an actual dataset, the Diabetes dataset from Kaggle. This has 10 features and 1 target,
so it is an instance of **multiple regression**, however we can train a model almost exactly as we did in the univariate case.

After doing a bit of EDA and massaging of the features, we will first consider separate regressions on a single feature of the dataset, and then run multiple regression on the whole set.
"""

# Download Kaggle Diabetes Dataset

from sklearn.datasets import load_diabetes

data_diabetes = load_diabetes(as_frame=True)
df_diabetes = pd.concat([data_diabetes.data, data_diabetes.target.rename('DiseaseProgression')], axis=1)

feature_names = df_diabetes.drop(columns=["DiseaseProgression"]).columns.tolist()

df_diabetes.head()

df_diabetes.info()

"""#### Features of the Diabetes Dataset

- **age**: age of the patient  
- **sex**: gender of the patient  
- **bmi**: body mass index (BMI)  
- **bp**:  mean blood pressure  
- **s1**:  measure of serum cholesterol levels  
- **s2**:  measure related to low-density lipoproteins (LDL)  
- **s3**:  measure of high-density lipoproteins (HDL)  
- **s4**:  measure of total cholesterol-to-HDL ratio  
- **s5**:  measure of serum triglycerides  
- **s6**:  measure of blood sugar levels  
- **DiseaseProgression**: Quantitative measure of diabetes disease progression one year after baseline (target variable)  


"""

# Always useful to create histograms of the features when possible; the layout and formatting are sometimes awkward, so
# I use the following:

df_diabetes.hist(figsize=(12,8), layout=(3,4),grid=False,edgecolor='black')
plt.tight_layout()
plt.show()

"""### Part A

**TODO:**

- In order to avoid any awkward moments when discussing the dataset, `rename` the column name 'sex' to 'gender'
  *in-place* and set the variable `a4a` to a numpy array of the feature/column names.
- Hint: if your answer starts `Index(...` then you have a Pandas data structure and not an ndarray as required.

"""

# Your answer here, NOT in the next cell (you may add additional cells if you wish)
# reference: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html
df_diabetes.rename(columns={"sex":"gender"}, inplace=True)
a4a = np.asarray(df_diabetes.columns)               # Replace the [] with appropriate ndarray

# Graded Answer
# DO NOT change this cell in any way

print(f'a4a = {a4a}')

"""### Part B

**TODO:**

- Create dataset in the form `X,y` from the dataframe by dropping the last column to create `X`, and just selecting the last column to make `y`

- Note: `sklearn`'s models are perfectly happy to work with dataframes, so we can just keep them as such and not convert to ndarrays.  Two advantages are: you don't have to reshape for input to the model, and you keep the feature names in case you need them later, e.g., when doing feature selection.

- Set `a4b` to the shape of `X`

"""

# Your answer here, NOT in the next cell (you may add additional cells if you wish)
X = df_diabetes.drop(columns=["DiseaseProgression"])
y = df_diabetes["DiseaseProgression"]

a4b = X.shape                  # Replace 0,0 with the shape of X

# Graded Answer
# DO NOT change this cell in any way

print(f'a4b = {a4b}')

"""### Part C: Training and Testing for Generalization

We will spend the next two lessons thinking about how to evaluate  models for generalization, but let's try a naive strategy
for now:  We will split the dataset into training and testing sets, and see how the model performs on  data it has never seen.
The disadvantage of this is that we have less training data, of course!

**TODO:**

- Use `sklearn`'s `train_test_split` to shuffle `X` and split it into 80% training data and 20% testing data with `random_state=42`
- Train a model `model_diabetes` on the training set, and then test it on the same set to find the training MSE.
- Assign the training MSE to `a4c`.
"""

# Your answer here, NOT in the next cell (you may add additional cells if you wish)
# reference: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

# train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# build a model, fit it, and make predictions
model_diabetes = LinearRegression()
diabetes_fit = model_diabetes.fit(X_train,y_train)
diabetes_predict_train = model_diabetes.predict(X_train)

# training MSE

a4c = mean_squared_error(y_train, diabetes_predict_train)              # Replace the 0 with the training mse

# Graded Answer
# DO NOT change this cell in any way

print(f'a4c = {a4c:.4f}')             # Will print to 4 decimal places

"""### Part D

**TODO:**

- Run the model created in Part C on the testing set to determine the test MSE.
- Set `a4d` to the test MSE.
"""

# Your answer here, NOT in the next cell (you may add additional cells if you wish)

diabetes_predict_test = model_diabetes.predict(X_test)

a4d = mean_squared_error(y_test, diabetes_predict_test)              # Replace the 0 with the test mse

# Graded Answer
# DO NOT change this cell in any way

print(f'a4d = {a4d:.4f}')         # Will print to 4 decimal places

"""### Part E

**TODO:**

Now try setting the percentage of the test size to different values, perhaps 0.1, 0.2, 0.3, 0.4, and 0.5 and run the above
cells and observe the training and testing MSEs.

Then choose the best answer below.


**How Does the Training‐Set Size Affect MSE?**

1.  Both **training MSE** and **testing MSE** remain exactly the same regardless of how many points you use, provided you keep the `random_state` fixed.  
2.  Both **training MSE** and **testing MSE** steadily converge to **zero** once you exceed a certain training‐set size threshold (e.g., 30 points).  
3.  **Training MSE** usually goes **up** slightly with a bigger training set (it’s harder to fit more points perfectly), but **testing MSE** tends to go **down** (the model generalizes better with more data).  
4.  Both **training MSE** and **testing MSE** decrease when the training set grows, because the model memorizes a larger volume of data and thus reduces all errors.


**NOTE: Before submitting your homework, set the percentage back to 0.2 (that is, 20%) as in the original problem and remember to Run All!**
"""

# Your answer here, NOT in the next cell (you may add additional cells if you wish)

# # 0.1
# # set train, test variables
# X_train1, X_test1, y_train1, y_test1 = train_test_split(X, y, test_size=0.1, random_state=42)
# # fit and predict
# diabetes_fit1 = model_diabetes.fit(X_train1,y_train1)
# diabetes_predict_train1 = model_diabetes.predict(X_train1)
# diabetes_predict_test1 = model_diabetes.predict(X_test1)
# # MSE of training and test data
# diabetes_train_mse1 = mean_squared_error(y_train1, diabetes_predict_train1)
# diabetes_testing_mse1 = mean_squared_error(y_test1, diabetes_predict_test1)
# # print results
# print("Test size 0.1 Train MSE:" , diabetes_train_mse1)
# print("Test size 0.1 Test MSE:" , diabetes_testing_mse1)

# # 0.2
# # set train, test variables
# X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y, test_size=0.2, random_state=42)
# # fit and predict
# diabetes_fit2 = model_diabetes.fit(X_train2,y_train2)
# diabetes_predict_train2 = model_diabetes.predict(X_train2)
# diabetes_predict_test2 = model_diabetes.predict(X_test2)
# # MSE of training and test data
# diabetes_train_mse2 = mean_squared_error(y_train2, diabetes_predict_train2)
# diabetes_testing_mse2 = mean_squared_error(y_test2, diabetes_predict_test2)
# # print results
# print("Test size 0.2 Train MSE:" , diabetes_train_mse2)
# print("Test size 0.2 Test MSE:" , diabetes_testing_mse2)

# # 0.3
# # set train, test variables
# X_train3, X_test3, y_train3, y_test3 = train_test_split(X, y, test_size=0.3, random_state=42)
# # fit and predict
# diabetes_fit3 = model_diabetes.fit(X_train3,y_train3)
# diabetes_predict_train3 = model_diabetes.predict(X_train3)
# diabetes_predict_test3 = model_diabetes.predict(X_test3)
# # MSE of training and test data
# diabetes_train_mse3 = mean_squared_error(y_train3, diabetes_predict_train3)
# diabetes_testing_mse3 = mean_squared_error(y_test3, diabetes_predict_test3)
# # print results
# print("Test size 0.3 Train MSE:" , diabetes_train_mse3)
# print("Test size 0.3 Test MSE:" , diabetes_testing_mse3)

# # 0.4
# # set train, test variables
# X_train4, X_test4, y_train4, y_test4 = train_test_split(X, y, test_size=0.4, random_state=42)
# # fit and predict
# diabetes_fit4 = model_diabetes.fit(X_train4,y_train4)
# diabetes_predict_train4 = model_diabetes.predict(X_train4)
# diabetes_predict_test4 = model_diabetes.predict(X_test4)
# # MSE of training and test data
# diabetes_train_mse4 = mean_squared_error(y_train4, diabetes_predict_train4)
# diabetes_testing_mse4 = mean_squared_error(y_test4, diabetes_predict_test4)
# # print results
# print("Test size 0.4 Train MSE:" , diabetes_train_mse4)
# print("Test size 0.4 Test MSE:" , diabetes_testing_mse4)

# # 0.5
# # set train, test variables
# X_train5, X_test5, y_train5, y_test5 = train_test_split(X, y, test_size=0.5, random_state=42)
# # fit and predict
# diabetes_fit5 = model_diabetes.fit(X_train5,y_train5)
# diabetes_predict_train5 = model_diabetes.predict(X_train5)
# diabetes_predict_test5 = model_diabetes.predict(X_test5)
# # MSE of training and test data
# diabetes_train_mse5 = mean_squared_error(y_train5, diabetes_predict_train5)
# diabetes_testing_mse5 = mean_squared_error(y_test5, diabetes_predict_test5)
# # print results
# print("Test size 0.5 Train MSE:" , diabetes_train_mse5)
# print("Test size 0.5 Test MSE:" , diabetes_testing_mse5)

# results
# Test size 0.1 Train MSE: 2880.326010197211
# Test size 0.1 Test MSE: 2743.911237757697
# Test size 0.2 Train MSE: 2868.5497028355776
# Test size 0.2 Test MSE: 2900.1936284934814
# Test size 0.3 Train MSE: 2924.0463790726394
# Test size 0.3 Test MSE: 2821.7509810013094
# Test size 0.4 Train MSE: 2946.853593349735
# Test size 0.4 Test MSE: 2832.9962397611494
# Test size 0.5 Train MSE: 2873.696790407302
# Test size 0.5 Test MSE: 2978.598328135722

# 1. not true at all - much observed variance in the results
# 2. not true at all - none of the results are anywhere close to 0
# 3. most of the instances were higher in the train MSE; this option uses less absolute language so I think this is it
# 4. there's a mix of increasing and decreasing

a4e = 3           # Replace the 0 with one of 1, 2, 3, 4

# Graded Answer
# DO NOT change this cell in any way

print(f'a4e = {a4e}')